name: Unit Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7']
        julia-arch: [x64]
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
  register:
    needs: test # Only run this once test is completed
    name: Register Package
    runs-on: ubuntu-latest
    steps:
    - uses: lukasgrunwald/julia-register-local@master
      with:
        localregistry: git@github.com:lukasgrunwald/CondMatRegistry.git
        ssh_keys: |
           ${{ secrets.REGISTRY_DEPLOY }}
    